# League of Legends Project

**Name(s)**: Landon Marchetti and Lyn Mansfield

**Website Link**: https://lyn-mansfield.github.io/league-pick-2-win/

import pandas as pd
import numpy as np
from pathlib import Path

import plotly.express as px
pd.options.plotting.backend = 'plotly'
import plotly.io as pio
pio.renderers.default = 'iframe'

from dsc80_utils import * # Feel free to uncomment and use this.

In [403]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Step 1: Introduction

Which legends are the most meta-defining? Difference in win rate between when it's banned vs when it's not

How important is the first kill of a game? 
- not important at all actually lol, the winrates are all the same no matter what

Which characters are the most banned? Which characters are the best?

What archetype of character's performance matters the most?

How important is early success?

The central question we will be looking at further is: How do character bans and archetypes influence competitive performance and define the meta in League of Legends? This question aims to explore how the types of champions that are banned or picked—especially based on their archetypes—affect individual and team performance in professional League of Legends matches.

## Step 2: Data Cleaning and Exploratory Data Analysis

What are "partial" rows missing from their data? <== me!

In [404]:
# TODO

from pathlib import Path

dataset_path = Path("./data/2025_LoL_clean_stats.csv")
# /data/2025_LoL_clean_stats.csv
data = pd.read_csv(dataset_path).drop(columns=['Unnamed: 0'])

In [405]:
player_data = data[data['damageshare'].notna()]

In [406]:
# Champion Play Frequency Graph
fig = px.line(player_data['champion'].value_counts(ascending=True), 
	labels={'index': 'Champion', 'value': 'Count'},
	title='Champion Play Frequencies'
	)
fig.write_html("univariate_analysis.html", full_html=False, include_plotlyjs='cdn')

In [407]:
fig = player_data['dpm'].hist()
fig.show()

In [408]:
player_rows = data[data['playername'].notna()]
team_rows = data[data['playername'].isna()]

In [409]:
x = player_rows.pivot_table(index='champion', columns='result', values='assists', aggfunc='count', fill_value=0)
#x['Popularity'] = x.sum(axis=1)
x['W/L Ratio'] = x['Won'] / x.sum(axis=1)
#x.sort_values(by='Popularity')
x = x.sort_values(by='W/L Ratio')
x

result        Lost  Won  W/L Ratio
champion
Illaoi           2    0       0.00
Heimerdinger     1    0       0.00
Katarina         4    0       0.00
...            ...  ...        ...
Akshan           1    5       0.83
Evelynn          0    2       1.00
Malzahar         0    2       1.00

[168 rows x 3 columns]

In [410]:
interesting_pt = team_rows.pivot_table(index='result', columns='firstblood', values='dpm', aggfunc='count', fill_value=0, margins=True)
print(interesting_pt.to_html())

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th>firstblood</th>
      <th>False</th>
      <th>True</th>
      <th>All</th>
    </tr>
    <tr>
      <th>result</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Lost</th>
      <td>2903</td>
      <td>2121</td>
      <td>5024</td>
    </tr>
    <tr>
      <th>Won</th>
      <td>2119</td>
      <td>2895</td>
      <td>5014</td>
    </tr>
    <tr>
      <th>All</th>
      <td>5022</td>
      <td>5016</td>
      <td>10038</td>
    </tr>
  </tbody>
</table>

## Bivariate Anaysis

In [411]:

dataset_path = Path("./data/2025_LoL_clean_stats.csv")
# /data/2025_LoL_clean_stats.csv
df = pd.read_csv(dataset_path) 
df['kill_participation'] = df['kills'] + df['assists']

player_rows = df[df['pick1'].isna()]

# Plot using pandas with plotly backend
fig = px.scatter(
    player_rows,
    x='kill_participation',
    y='earnedgold',
    hover_data='playername',
    title='Earned Gold vs Kill Participation (Kills + Assists)'
)

fig.show()

In [412]:
avg_deaths = df.groupby('result')['deaths'].mean().reset_index()

# Plot as bar chart
fig = avg_deaths.plot(
    kind='bar',
    x='result',
    y='deaths',
    title='Average Deaths by Match Result',
    labels={'result': 'Match Result', 'deaths': 'Average Deaths'},
)

fig.show()

In [413]:
avg_dmg_mitigated = df.groupby('position')['damagemitigatedperminute'].mean().reset_index()
avg_dmg_mitigated = avg_dmg_mitigated.query("position != 'team'")

# Plot bar chart
fig = avg_dmg_mitigated.plot(
    kind='bar',
    x='position',
    y='damagemitigatedperminute',
    title='Average Damage Mitigated per Minute by Position',
    labels={'position': 'Position', 'damagemitigatedperminute': 'Avg Damage Mitigated / Minute'}
)

fig.show()

## Step 3: Assessment of Missingness

In [414]:
data['missing'] = data['teamid'].isna()

actual_missing = data[data['missing'] == True]['league'].value_counts(normalize=True)
actual_present = data[data['missing'] == False]['league'].value_counts(normalize=True)


combined = pd.concat([actual_missing, actual_present], axis=1).fillna(0)
combined.columns = ['missing', 'present']

observed = 0.5 * np.sum(np.abs(combined['missing'] - combined['present']))

n_permutations = 1000
tvd_stats = []

shuffled_df = data.copy()
for _ in range(n_permutations):
    
    shuffled = np.random.permutation(data['missing'])
    shuffled_df['shuffled_missing'] = shuffled

    dist_missing = shuffled_df[shuffled_df['shuffled_missing'] == True ]['league'].value_counts(normalize=True)
    dist_present = shuffled_df[shuffled_df['shuffled_missing'] == False ]['league'].value_counts(normalize=True)
    
    comb = pd.concat([dist_missing, dist_present], axis=1).fillna(0)
    comb.columns = ['missing', 'present']
    stat = 0.5 * np.sum(np.abs(comb['missing'] - comb['present']))
    tvd_stats.append(stat)


p_val = np.mean(np.array(tvd_stats) >= observed)
p_val

np.float64(0.0)

In [415]:
hist = go.Histogram(
    x=tvd_stats,
    nbinsx=30,
    histnorm='probability density',
    name='Permutation Distribution',
    opacity=0.75
)

# Add vertical line for observed TVD
vline = go.Scatter(
    x=[observed, observed],
    y=[0, max(np.histogram(tvd_stats, bins=30, density=True)[0])],
    mode='lines',
    line=dict(color='red', dash='dash'),
    name=f'Observed TVD = {observed:.3f}'
)

# Create and display the plot
fig = go.Figure(data=[hist, vline])
fig.update_layout(
    title='Empirical Distribution of TVD Statistic',
    xaxis_title='Total Variation Distance (TVD)',
    yaxis_title='Density',
    template='plotly_white'
)
fig.show()

## Missingness Dependency, not dependent

In [416]:
actual_missing_2 = data[data['missing'] == True]['side'].value_counts(normalize=True)
actual_present_2 = data[data['missing'] == False]['side'].value_counts(normalize=True)


combined_2 = pd.concat([actual_missing_2, actual_present_2], axis=1).fillna(0)
combined_2.columns = ['missing', 'present']

observed_2 = 0.5 * np.sum(np.abs(combined_2['missing'] - combined_2['present']))

n_permutations = 1000
tvd_stats_2 = []

shuffled_df_2 = data.copy()
for _ in range(n_permutations):
    
    shuffled_2 = np.random.permutation(data['missing'])
    shuffled_df_2['shuffled_missing'] = shuffled_2

    dist_missing_2 = shuffled_df_2[shuffled_df_2['shuffled_missing'] == True ]['side'].value_counts(normalize=True)
    dist_present_2 = shuffled_df_2[shuffled_df_2['shuffled_missing'] == False ]['side'].value_counts(normalize=True)
    
    comb_2 = pd.concat([dist_missing_2, dist_present_2], axis=1).fillna(0)
    comb_2.columns = ['missing', 'present']
    stat_2 = 0.5 * np.sum(np.abs(comb_2['missing'] - comb_2['present']))
    tvd_stats_2.append(stat_2)


p_val_2 = np.mean(np.array(tvd_stats_2) >= observed_2)
p_val_2

np.float64(0.118)

In [417]:
hist_2 = go.Histogram(
    x=tvd_stats_2,
    nbinsx=30,
    histnorm='probability density',
    name='Permutation Distribution',
    opacity=0.75
)

# Vertical line for observed TVD
vline_2 = go.Scatter(
    x=[observed_2, observed_2],
    y=[0, max(np.histogram(tvd_stats_2, bins=30, density=True)[0])],
    mode='lines',
    line=dict(color='red', dash='dash'),
    name=f'Observed TVD = {observed_2:.3f}'
)

# Create and show the plot
fig_2 = go.Figure(data=[hist_2, vline_2])
fig_2.update_layout(
    title="Empirical Distribution of TVD for 'side' vs Missingness in 'teamid'",
    xaxis_title='Total Variation Distance (TVD)',
    yaxis_title='Density',
    template='plotly_white'
)

fig_2.show()

In [418]:
# TODO

def univariate_plots(df, title):
    pdf_pages = PdfPages(f'univariate_plots_{title}.pdf')

    plt.figure()

    for column in df.columns:
        fig, ax = plt.subplots()
        ax.hist(df[column], bins=200)
        ax.set_title(f'Graph of {column}')
        pdf_pages.savefig(fig)
        plt.close(fig)
    
    pdf_pages.close()

def bivariate_plot(df, categorical_column, target_column, title):
    pdf_pages = PdfPage(f'bivariate_plots_{title}.pdf')

    plt.figure()
    
    for column in df.columns:
        fig, ax = plt.subplots()
        ax.hist(df[column])
        ax.set_title(f'Graph of {column}')
        pdf_pages.savefig(fig)
        plt.close(fig)
    
    pdf_pages.close()

In [419]:
num_missing = data.apply(pd.isna).sum()
num_missing = num_missing / data.shape[0] * 100

fig = px.bar(num_missing[num_missing != 0].sort_values(), 
	labels={'index': 'Column name', 'value': '% missing'},
	title='Data missing from partial rows'
	)
fig.show()

In [420]:
fig = player_data['damagetakenperminute'].hist()
fig.write_html("univariate_analysis.html")

In [421]:
# 

type_frequencies = data.dtypes.value_counts()
type_frequencies.index = type_frequencies.index.map(str)
fig = px.bar(type_frequencies, 
	labels={'index': 'Data type', 'value': 'Frequency'}
	)
fig.update_layout(
    title={
        'text': 'Data Type Frequencies of Relevant Data',
        #'font': {'size': 24}
    }
)
fig.write_html('data_type_frequency.html')

## Step 4: Hypothesis Testing

In [422]:
player_rows['result'] = player_rows['result'].apply(lambda x: 1 if x == "Won" else 0)
champion_win_rates = player_rows.groupby("champion")['result'].mean()
champion_win_rates = champion_win_rates.rename("Win rate")
champion_win_rates

champion
Aatrox    0.51
Ahri      0.49
Akali     0.51
          ...
Zilean    0.56
Zoe       0.53
Zyra      0.52
Name: Win rate, Length: 168, dtype: float64

In [423]:
times_picked = player_rows['champion'].value_counts()
times_picked = times_picked.rename('Times picked')

In [424]:
ban_columns = team_rows[['ban1', 'ban2', 'ban3', 'ban4', 'ban5']]
bans_series = ban_columns.stack()
champion_ban_rates = bans_series.value_counts() / bans_series.shape[0] * 5 
# multiply by 5 because each team bans 5 champions, so there are (ban_series.shape[0] / 5) games total
champion_ban_rates = champion_ban_rates.rename('Ban rate')
champion_ban_rates

Kalista    2.28e-01
Vi         2.03e-01
Varus      1.95e-01
             ...
Sona       1.00e-04
Nasus      1.00e-04
Illaoi     1.00e-04
Name: Ban rate, Length: 168, dtype: float64

In [425]:
merged_df = pd.DataFrame(champion_win_rates)
merged_df = merged_df.merge(champion_ban_rates, left_index=True, right_index=True)
merged_df = merged_df.merge(times_picked, left_index=True, right_index=True)

merged_df = merged_df.reset_index().rename(columns={'index': 'Champion name'})
merged_df

    Champion name  Win rate  Ban rate  Times picked
0          Aatrox      0.51  1.07e-02           396
1            Ahri      0.49  5.18e-02           903
2           Akali      0.51  4.20e-02           362
..            ...       ...       ...           ...
164        Zilean      0.56  3.00e-04            16
165           Zoe      0.53  6.90e-03            36
166          Zyra      0.52  9.40e-02           370

[167 rows x 4 columns]

In [426]:
from sklearn.linear_model import LinearRegression
from scipy import stats

# Reshape X for sklearn (requires 2D array)
X = merged_df[['Ban rate']]
y = merged_df['Win rate']

# Fit model
model = LinearRegression().fit(X, y)

# Calculate p-value manually
slope = model.coef_[0]
intercept = model.intercept_
predictions = model.predict(X)

# Residuals and standard error
residuals = y - predictions
dof = len(X) - 2  # Degrees of freedom
mse = np.sum(residuals**2) / dof
se_slope = np.sqrt(mse / np.sum((X['Ban rate'] - X['Ban rate'].mean())**2))
t_stat = slope / se_slope
p_value = 2 * stats.t.sf(np.abs(t_stat), dof)
p_value
# Lyn: P-value is pretty high

np.float64(0.2591276992799126)

In [427]:
fig = px.scatter(merged_df, x='Ban rate', y='Win rate', hover_data='Champion name')
fig.add_hline(
    y=0.5,
    line_dash="dash",  # Makes the line dashed
    line_color="black",  # Adjust color as needed
    line_width=2,
    opacity=0.2,
)

# Add linear regression trace
fig.add_trace(
    go.Scatter(
        x=merged_df['Ban rate'],
        y=model.predict(merged_df[['Ban rate']]),
        mode='lines',
        name='Regression Line',
        opacity=0.3,
        line=dict(color='red')
))

fig.show()
# Lyn: Looks like there's a lot of outlier data from champions that nobody picks or bothers banning

In [428]:
#merged_df.sort_values(by='Times picked').plot.bar(x='Champion name', y='Times picked')
# Filter out rarely picked champions to see if our model improves
print(sifted_df['Times picked'].sum() / 1000)
# Lyn: Let's try keeping only champions that are picked one time in every thousand, that seems fair
sifted_df = merged_df.query("`Times picked` > 50")
sifted_df.shape[0] / merged_df.shape[0]

48.957

0.6167664670658682

In [429]:
from sklearn.linear_model import LinearRegression
from scipy import stats

# Reshape X for sklearn (requires 2D array)
X = sifted_df[['Ban rate']]
y = sifted_df['Win rate']

# Fit model
model = LinearRegression().fit(X, y)

# Calculate p-value manually
slope = model.coef_[0]
intercept = model.intercept_
predictions = model.predict(X)

# Residuals and standard error
residuals = y - predictions
dof = len(X) - 2  # Degrees of freedom
mse = np.sum(residuals**2) / dof
se_slope = np.sqrt(mse / np.sum((X['Ban rate'] - X['Ban rate'].mean())**2))
t_stat = slope / se_slope
p_value = 2 * stats.t.sf(np.abs(t_stat), dof)
p_value
# Lyn: Much better p-value! Looks like we can conclude that ban rates are correlated with win rate.

np.float64(0.024711277263067488)

In [430]:
fig = px.scatter(sifted_df, x='Ban rate', y='Win rate', hover_data='Champion name')
fig.add_hline(
    y=0.5,
    line_dash="dash",  # Makes the line dashed
    line_color="black",  # Adjust color as needed
    line_width=2,
    opacity=0.2,
)

# Add linear regression trace
fig.add_trace(
    go.Scatter(
        x=sifted_df['Ban rate'],
        y=model.predict(sifted_df[['Ban rate']]),
        mode='lines',
        name='Regression Line',
        opacity=0.3,
        line=dict(color='red')
))

fig.show()

## Step 5: Framing a Prediction Problem


Now that we can see that win-rates are pretty strongly correlated to ban-rates, it seems safe to assume that the presence of certain champions have a dramatic effect on the outcome of a game. After all, some champions seem be a lot stronger than others, and many have higher than average win-rates. This begs the question: **how well can we predict whether a team will win or lose based on other game statistics?**

To build off of our hypothesis testing, we will begin the predction with the champions players pick at the beginning of the game. As such, our inputs will be the five champions that each team chooses, and the outputs will classify whether the model thinks those picks will lead to a win or a loss. We do this to see if we can predict if a team will win or lose purely based off of the champions they choose, or must there be some skill and preformance taken into account.

## Step 6: Baseline Model

In [431]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression  
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OneHotEncoder, StandardScaler, QuantileTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score

# uses picks only to predict result

dff = df.copy()
dff = dff.dropna(subset=['pick1'])
dff['result'] = dff['result'].str.strip().str.lower().map({'won': 1, 'lost': 0})


X = dff[['pick1', 'pick2', 'pick3', 'pick4', 'pick5']]
y = dff['result']
categorical_features = ['pick1', 'pick2', 'pick3', 'pick4', 'pick5']
categorical_transformer = OneHotEncoder(handle_unknown='ignore')

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', categorical_transformer, categorical_features)
    ]
)

pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier',  RandomForestClassifier(random_state=42))
])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
cv_scores = cross_val_score(pipeline, X, y, cv=5, scoring='accuracy')

pipeline.fit(X_train, y_train)

train_score = pipeline.score(X_train, y_train)
test_score = pipeline.score(X_test, y_test)

cv_scores.mean()

np.float64(0.5077003501750875)

n_estimators: More trees generally improve performance but increase training time.

max_depth: A shallow tree might underfit the data, while a very deep tree might overfit. find if a limited depth helps or if 
unlimited is best. 

min_samples_split: Increasing this value can help prevent the model from learning noise in the training data.

## Step 7: Final Model

In [432]:
# uses picks, kills, and assists to predict result
def model(df):
    dff = df.copy()
    X = dff[['pick1', 'pick2', 'pick3', 'pick4', 'pick5', 'kills', 'assists']]
    y = dff['result']

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42)

    categorical_features = ['pick1', 'pick2', 'pick3', 'pick4', 'pick5']
    numerical_standard = ['kills']
    numerical_quantile = ['assists']
    
    preprocessor = ColumnTransformer(transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features),
        ('scale', StandardScaler(), numerical_standard),
        ('quantile', QuantileTransformer(output_distribution='normal'), numerical_quantile)
    ])
    
    pipeline = Pipeline(steps=[
        ('preprocessor', preprocessor),
        ('classifier', RandomForestClassifier(random_state=42))
    ])
    
    param_grid = {
        'classifier__n_estimators': [5, 10, 25, 50, 100],
        'classifier__max_depth': [5, 10, None],
        'classifier__min_samples_split': [2, 5]
    }
    
    grid_search = GridSearchCV(pipeline, param_grid, cv=5, scoring='accuracy', n_jobs=-1)
    grid_search.fit(X_train, y_train)
    
    best_param = grid_search.best_params_
    acc = grid_search.best_score_
    print(f"accuracy: {acc}, best parameters: {best_param}")

    return grid_search

# accuracy: 0.8439622420262666, best parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 5, 'classifier__n_estimators': 100}

final_model = model(team_rows)

accuracy: 0.8434620174346202, best parameters: {'classifier__max_depth': None, 'classifier__min_samples_split': 5, 'classifier__n_estimators': 100}

## Step 8: Fairness Analysis

In [433]:
# Are we being fair to teams that did not just do damage?

median_kills = team_rows['kills'].median()
team_rows_kills_sort = team_rows.sort_values(by='kills', ignore_index=True)
bottom_half = team_rows_kills_sort.query("kills <= @median_kills")
top_half = team_rows_kills_sort.query("kills > @median_kills")

top_half_predictions = final_model.predict(top_half)
top_half_accurate_series = top_half_predictions == top_half['result']
top_accuracy = top_half_accurate_series.mean()

bottom_half_predictions = final_model.predict(bottom_half)
bottom_half_accurate_series = bottom_half_predictions == bottom_half['result']
bottom_accuracy = bottom_half_accurate_series.mean()

observed_abs_diff = np.abs(top_accuracy - bottom_accuracy)
observed_abs_diff

np.float64(0.033950604659566896)

In [434]:
accurate_series = pd.concat([bottom_half_accurate_series, top_half_accurate_series], ignore_index=True)
team_rows_kills_sort['accurate'] = accurate_series

n_permutations = 1024

abs_diffs = []
shuffled_team_rows = team_rows_kills_sort.copy()
for _ in range(n_permutations):
    shuffled_kills = np.random.permutation(shuffled_team_rows['kills'])
    shuffled_team_rows['kills'] = shuffled_kills

    high_kills_accuracy_rate = shuffled_team_rows.query("kills <= @median_kills")['accurate'].mean()
    low_kills_accuracy_rate = shuffled_team_rows.query("kills > @median_kills")['accurate'].mean()
    
    abs_diff = np.abs(high_kills_accuracy_rate - low_kills_accuracy_rate)
    abs_diffs.append(abs_diff)

p_val = np.mean(np.array(abs_diffs) >= observed_abs_diff)
p_val

np.float64(0.0)

In [436]:
fair_hist = go.Histogram(
    x=abs_diffs,
    nbinsx=30,
    histnorm='probability density',
    name='Absolute Difference Distribution',
    opacity=0.75
)

# Vertical line for observed TVD
fair_vline = go.Scatter(
    x=[observed_abs_diff, observed_abs_diff],
    y=[0, max(np.histogram(abs_diffs, bins=30, density=True)[0])],
    mode='lines',
    line=dict(color='red', dash='dash'),
    name=f'Observed Abs. Diff. = {observed_abs_diff:.3f}'
)

# Create and show the plot
fig = go.Figure(data=[fair_hist, fair_vline])
fig.update_layout(
    title="Empirical Distribution of Absolute Difference",
    xaxis_title='Absolute Difference',
    yaxis_title='Density',
    template='plotly_white'
)

fig.write_html("fairness_hist.html", full_html=False, include_plotlyjs='cdn')
fig.show()